[package]
name = "sip"
version = "0.1.0"
edition = "2021"

[dependencies]
lexer = {path = "./lexer"}
lex_validator = {path = "./lex_validator"}
parser = {path = "./parser"}
symboltable = {path = "./symboltable"}
cwrite = {path = "./cwrite"}